$(document).ready(function(){fun_multilang_adapter();fun_register_all_event();fun_get_ipcamera_parameters();fun_get_protocal_ability();fun_get_protocol_support();});function fun_register_all_event(){$("#button_server_port_restore,#button_server_port_save").click(function(){if(this.id.toString()=="button_server_port_restore"){fun_restore_server_port();}else if(this.id.toString()=="button_server_port_save"){fun_save_server_prot(true);}});$("#button_tips_confirm,#button_tips_cancel").click(function(){if(this.id.toString()=="button_tips_confirm"){fun_show_tips_dialog(false);fun_save_server_prot(false);return;}
fun_show_tips_dialog(false);});$("#button_server_port_refresh").click(function(){fun_refresh_server_port();fun_get_protocal_ability();fun_get_protocol_support();});$("#input_http_port,#input_https_port,#input_rtsp_port,#input_tcp_port,#input_flash_port").keydown(function(){var objid=this.id.toString();fun_on_input_keydown(objid);});$("#input_http_port,#input_https_port,#input_rtsp_port,#input_tcp_port,#input_flash_port").keyup(function(){var objid=this.id.toString();fun_on_input_keyup(objid);});}
function fun_multilang_adapter(){translate_page_item(TARGET_PAGE_SUB_PORT,"serverport","div_table_server_port_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"httpport","div_http_port_name_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"httpsport","div_https_port_name_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"rtspport","div_rtsp_port_name_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"tcpport","div_tcp_port_name_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"flashport","div_flash_port_name_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"save","button_server_port_save",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"restore","button_server_port_restore",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_SUB_PORT,"portsetting","div_rtsp_information_title_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"protosetting","div_protocol_information_title_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_GENERAL,"notep2pcode","p_note_reboot",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PORT,"httptips","input_http_port",ITEM_TYPE_TOOLTIP);translate_page_item(TARGET_PAGE_SUB_PORT,"httpstips","input_https_port",ITEM_TYPE_TOOLTIP);translate_page_item(TARGET_PAGE_COMMON,"confirm","button_tips_confirm",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"cancel","button_tips_cancel",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"refresh","button_server_port_refresh",ITEM_TYPE_VALUE);var strdefault=translate_page_item(TARGET_PAGE_COMMON,"default","",ITEM_TYPE_NONE);$("#div_http_port_tips_text").text("[1..65535, "+strdefault+" 80]");$("#div_https_port_tips_text").text("[1..65535, "+strdefault+" 443]");$("#div_rtsp_port_tips_text").text("[1..65535, "+strdefault+" 554]");$("#div_tcp_port_tips_text").text("[1..65535, "+strdefault+" 6000]");$("#div_rtmp_port_tips_text").text("[1..65535, "+strdefault+" 1935]");}
var g_http_port=0;var g_https_port=0;var g_canset_flash=false;function fun_get_ipcamera_parameters(){sdk_getipcparam("/action/get?subject=netserv",function(result){if(result!=false){$xml=$(result);var httpport=$xml.find("http").text();var httpsport=$xml.find("https").text();var rtspport=$xml.find("rtsp").text();var tcpport=$xml.find("tcp").text();var flashport=$xml.find("rtmp").text();g_http_port=httpport;g_https_port=httpsport;document.getElementById("input_http_port").value=httpport;document.getElementById("input_https_port").value=httpsport;document.getElementById("input_rtsp_port").value=rtspport;document.getElementById("input_tcp_port").value=tcpport;if(flashport.length>0){document.getElementById("input_flash_port").value=flashport;$("#input_flash_port").removeAttr("readonly");g_canset_flash=true;$("#div_rtmp_port_tips").css("display","block");}}});}
function fun_get_protocal_ability(){sdk_getipcparam("/action/get?subject=devability",function(result){if(result!=false){$xml=$(result);var protomask=$xml.find("nvrproto").text();var xmask=parseInt(protomask);var featrueab=$xml.find("featrueab").text();if(!(parseInt(featrueab)&0x08)){$("#div_server_port_item_https").css("display","none");}
if(xmask&1){$("#div_protocol_onvif").css("display","block");}else{$("#div_protocol_onvif").css("display","none");}
if(xmask&1<<1){$("#div_protocol_dh").css("display","block");}else{$("#div_protocol_dh").css("display","none");}
if(xmask&1<<2){$("#div_protocol_hk").css("display","block");}else{$("#div_protocol_hk").css("display","none");}
if(xmask&1<<3){$("#div_protocol_hb").css("display","block");}else{$("#div_protocol_hb").css("display","none");}
if(xmask&1<<4){$("#div_protocol_al").css("display","block");}else{$("#div_protocol_al").css("display","none");}
if(xmask&1<<5){$("#div_protocol_xm").css("display","block");}else{$("#div_protocol_xm").css("display","none");}
if(xmask&1<<9){$("#div_protocol_ts").css("display","block");}else{$("#div_protocol_ts").css("display","none");}}});}
var gdevname,gdatefmt,gtimefmt,glanguage,gp2p,gtelnet;function fun_get_protocol_support(){sdk_getipcparam("/action/get?subject=devpara",function(result){if(result!=false){$xml=$(result);var protomask=$xml.find("nvrproto").text();gdevname=$xml.find("name").text();gdatefmt=$xml.find("datefmt").text();gtimefmt=$xml.find("timefmt").text();glanguage=$xml.find("language").text();gp2p=$xml.find("p2p").text();gtelnet=$xml.find("telnet").text();var xmask=parseInt(protomask);if(xmask&1){$("#check_enable_onvif").prop("checked",true);}else{$("#check_enable_onvif").prop("checked",false);}
if(xmask&1<<1){$("#check_enable_dh").prop("checked",true);}else{$("#check_enable_dh").prop("checked",false);}
if(xmask&1<<2){$("#check_enable_hk").prop("checked",true);}else{$("#check_enable_hk").prop("checked",false);}
if(xmask&1<<3){$("#check_enable_hb").prop("checked",true);}else{$("#check_enable_hb").prop("checked",false);}
if(xmask&1<<4){$("#check_enable_al").prop("checked",true);}else{$("#check_enable_al").prop("checked",false);}
if(xmask&1<<5){$("#check_enable_xm").prop("checked",true);}else{$("#check_enable_xm").prop("checked",false);}
if(xmask&1<<9){$("#check_enable_ts").prop("checked",true);}else{$("#check_enable_ts").prop("checked",false);}}});}
function fun_save_protocol(){var enableonvif=$("#check_enable_onvif").prop("checked")?1:0;var enablehk=$("#check_enable_hk").prop("checked")?1:0;var enabledh=$("#check_enable_dh").prop("checked")?1:0;var enableal=$("#check_enable_al").prop("checked")?1:0;var enablexm=$("#check_enable_xm").prop("checked")?1:0;var enablehb=$("#check_enable_hb").prop("checked")?1:0;var enablets=$("#check_enable_ts").prop("checked")?1:0;var tagproto=(enablets<<9)+(enablexm<<5)+(enableal<<4)+(enablehb<<3)+(enablehk<<2)+(enabledh<<1)+enableonvif;var targetxml='<?xml version="1.0" encoding="utf-8"?>'+'<request>'+'<devpara>'+'<name>'+gdevname+'</name>'+'<datefmt>'+gdatefmt+'</datefmt>'+'<timefmt>'+gtimefmt+'</timefmt>'+'<language>'+glanguage+'</language>'+'<p2p>'+gp2p+'</p2p>'+'<telnet>'+gtelnet+'</telnet>'+'<nvrproto>'+String(tagproto)+'</nvrproto>'+'</devpara>'+"</request>";var strsuc=translate_page_item(TARGET_PAGE_TIPSTEXT,"infosave","",ITEM_TYPE_NONE);var failed=translate_page_item(TARGET_PAGE_TIPSTEXT,"errset","",ITEM_TYPE_NONE);var auth=translate_page_item(TARGET_PAGE_TIPSTEXT,"errauthority","",ITEM_TYPE_NONE);var request=translate_page_item(TARGET_PAGE_TIPSTEXT,"errrequest","",ITEM_TYPE_NONE);sdk_setipcparam("/action/set?subject=devpara",targetxml,function(result){if(result==true){if(g_change_https){window.location.href="login.html";}else{parent.fun_show_tips_dialog(strsuc);}}else if(result==400){parent.fun_show_tips_dialog(request,0);}else if(result==403){parent.fun_show_tips_dialog(auth,0);}else{parent.fun_show_tips_dialog(failed,0);}});}
function fun_restore_server_port(){document.getElementById("input_http_port").value="80";document.getElementById("input_https_port").value="443";document.getElementById("input_rtsp_port").value="554";document.getElementById("input_tcp_port").value="6000";if(g_canset_flash){document.getElementById("input_flash_port").value="1935";}
$("#check_enable_onvif").prop("checked",true);$("#check_enable_dh").prop("checked",false);$("#check_enable_hk").prop("checked",false);$("#check_enable_hb").prop("checked",false);$("#check_enable_al").prop("checked",false);$("#check_enable_xm").prop("checked",false);$("#check_enable_ts").prop("checked",false);}
function fun_refresh_server_port(){fun_get_ipcamera_parameters();}
function fun_check_value(listvalue,listobj){var index=0;var tempx=0;var cmpcnt=0;for(var i=0;i<listvalue.length;i++)
{cmpcnt=0;tempx=0;var val=listvalue[i];if(val<=0||val>65535)
{$("#"+listobj[index]).focus();$("#"+listobj[index]).select();break;}
for(var j=0;j<listvalue.length;j++){val1=listvalue[j];if(val1===val){++cmpcnt;}
if(cmpcnt>=2){$("#"+listobj[tempx]).focus();$("#"+listobj[tempx]).select();break;}
++tempx;}
if(cmpcnt>=2){break;}
++index;}}
var g_tips_https=false;var g_change_https=false;function fun_save_server_prot(bcheck){var http=document.getElementById("input_http_port").value;var https=document.getElementById("input_https_port").value;var rtsp=document.getElementById("input_rtsp_port").value;var tcp=document.getElementById("input_tcp_port").value;var rtmp=document.getElementById("input_flash_port").value;var targetxml='<?xml version="1.0" encoding="utf-8"?>'+'<request>'+'<netserv>'+'<http>'+http+'</http>'+'<https>'+https+'</https>'+'<rtsp>'+rtsp+'</rtsp>'+'<tcp>'+tcp+'</tcp>'+'<rtmp>'+rtmp+'</rtmp>'+'</netserv>'+'</request>';if(!(http>=1&&http<=65535&&https>=1&&https<=65535&&rtsp>=1&&rtsp<=65535&&tcp>=1&&tcp<=65535&&rtmp>=1&&rtmp<=65535)||http==https||http==rtsp||http==tcp||http==rtmp||https==rtsp||https==tcp||https==rtmp||rtsp==tcp||rtsp==rtmp||tcp==rtmp){var listval=new Array(http,https,rtsp,tcp,rtmp);var listobj=new Array("input_http_port","input_https_port","input_rtsp_port","input_tcp_port","input_flash_port");fun_check_value(listval,listobj);var strerrinput=translate_page_item(TARGET_PAGE_TIPSTEXT,"errinput","",ITEM_TYPE_NONE);parent.fun_show_tips_dialog(strerrinput,0);return;}
if(http!=g_http_port&&bcheck){g_tips_https=false;fun_show_tips_dialog(true);return;}
if(https!=g_https_port&&bcheck){g_tips_https=true;fun_show_tips_dialog(true);return;}else if(https!=g_https_port){g_change_https=true;}
var strsuc=translate_page_item(TARGET_PAGE_TIPSTEXT,"infosave","",ITEM_TYPE_NONE);var failed=translate_page_item(TARGET_PAGE_TIPSTEXT,"errset","",ITEM_TYPE_NONE);var auth=translate_page_item(TARGET_PAGE_TIPSTEXT,"errauthority","",ITEM_TYPE_NONE);var request=translate_page_item(TARGET_PAGE_TIPSTEXT,"errrequest","",ITEM_TYPE_NONE);sdk_setipcparam("/action/set?subject=netserv",targetxml,function(result){if(result==true){fun_save_protocol();}else if(result==400){parent.fun_show_tips_dialog(request,0);}else if(result==403){parent.fun_show_tips_dialog(auth,0);}else{parent.fun_show_tips_dialog(failed,0);}});}
function fun_show_tips_dialog(bshow){if(g_tips_https){translate_page_item(TARGET_PAGE_SUB_PORT,"httpstips","div_tips_text",ITEM_TYPE_TEXT);}else{translate_page_item(TARGET_PAGE_SUB_PORT,"httptips","div_tips_text",ITEM_TYPE_TEXT);}
if(bshow){$("#div_tips_dialog").dialog({modal:true,title:"",width:373,height:212,resizable:false});}else{$("#div_tips_dialog").dialog("destroy");}}
function fun_on_input_keydown(objid){var event=arguments.callee.caller.arguments[0]||window.event;if(!((event.keyCode>=48&&event.keyCode<=57)||(event.keyCode>=96&&event.keyCode<=105))&&(event.keyCode!=46)&&(event.keyCode!=8)){event.returnValue=false;event.preventDefault();return false;}}
function fun_on_input_keyup(objid){var cruval=parseInt($("#"+objid).val());if(!cruval){$("#"+objid).val("");}else{$("#"+objid).val(cruval.toString());}}