$(document).ready(function(){fun_multilang_adapter();fun_register_events();fun_get_pppoe_parameters();});function fun_register_events(){$("#button_pppoe_save,#button_pppoe_restore").click(function(){if(this.id.toString()=="button_pppoe_save"){fun_save_pppoe_parameters();}else if(this.id.toString()=="button_pppoe_restore"){fun_restore_pppoe_parameters();}});$("#check_enable_pppoe").click(function(){var enabled=document.getElementById("check_enable_pppoe").checked;if(enabled){$("#input_user_name,#input_password").removeAttr("disabled");}else{$("#input_user_name,#input_password").attr("disabled","disabled");}});$("#button_pppoe_refresh").click(function(){fun_refresh_pppoe();});}
function fun_password_eye_showorhide(eyestatus){var password=document.getElementById("input_password");if(eyestatus==0){$("#password_eye_show").show();$("#password_eye_hide").hide();password.type="text";}else{$("#password_eye_hide").show();$("#password_eye_show").hide();password.type="password";}}
function fun_multilang_adapter(){translate_page_item(TARGET_PAGE_SUB_PPPOE,"pppoetitle","div_title_pppoe_text",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PPPOE,"enablepppoe","label_enable_pppoe_declare",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"username","div_pppoe_username_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"password","div_pppoe_password_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_PPPOE,"connectsta","div_pppoe_connectstatus_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"ipaddress","div_pppoe_ipaddr_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"save","button_pppoe_save",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"restore","button_pppoe_restore",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"refresh","button_pppoe_refresh",ITEM_TYPE_VALUE);input_edit_restriction("input_user_name",EDIT_RESTRICTION_XMLSTD,32);input_edit_restriction("input_password",EDIT_RESTRICTION_PASSWORD,32);}
function fun_get_pppoe_parameters(){sdk_getipcparam("/action/get?subject=pppoe",function(result){if(result!=false){$xml=$(result);var enable=$xml.find("active").text();var username=$xml.find("username").text();var password=$xml.find("password").text();if(enable==1){document.getElementById("check_enable_pppoe").checked=true;$("#input_user_name,#input_password").removeAttr("disabled");}else{document.getElementById("check_enable_pppoe").checked=false;$("#input_user_name,#input_password").attr("disabled","disabled");}
document.getElementById("input_user_name").value=username;document.getElementById("input_password").value=password;}});sdk_getipcparam("/action/get?subject=pppoestat",function(result){if(result==false)
return;var strconnected=translate_page_item(TARGET_PAGE_COMMON,"connected","",ITEM_TYPE_NONE);var strdisconnected=translate_page_item(TARGET_PAGE_COMMON,"disconnected","",ITEM_TYPE_NONE);var strstatus = 0;var xmldoc = loadXMLString(String(result));if (xmldoc != null) {strstatus = xmldoc.getElementsByTagName("link")[0].textContent;}var straddress=$(result).find("addr").text();if(strstatus==0){$("#div_pppoe_connectstatus_value").text(strdisconnected);}else{$("#div_pppoe_connectstatus_value").text(strconnected);}
if(straddress.length>0){$("#div_pppoe_ipaddr_value").text(straddress);}});}
function fun_refresh_pppoe(){fun_get_pppoe_parameters();}
function fun_save_pppoe_parameters(){var enable=document.getElementById("check_enable_pppoe").checked;var username=document.getElementById("input_user_name").value;var password=document.getElementById("input_password").value;if(enable){enable="1";}else{enable="0";}
var passreg=/.{0,32}/;if(!passreg.test(password)){var errinput=translate_page_item(TARGET_PAGE_TIPSTEXT,"errinput","",ITEM_TYPE_NONE);parent.fun_show_tips_dialog(errinput,0);return;}
var targetxml='<?xml version="1.0" encoding="utf-8"?>'+'<request>'+'<pppoe>'+'<active>'+enable+'</active>'+'<username>'+username+'</username>'+'<password>'+password+'</password>'+'</pppoe>'+'</request>';var strsuc=translate_page_item(TARGET_PAGE_TIPSTEXT,"infosave","",ITEM_TYPE_NONE);var request=translate_page_item(TARGET_PAGE_TIPSTEXT,"errrequest","",ITEM_TYPE_NONE);var auth=translate_page_item(TARGET_PAGE_TIPSTEXT,"errauthority","",ITEM_TYPE_NONE);var failed=translate_page_item(TARGET_PAGE_TIPSTEXT,"errset","",ITEM_TYPE_NONE);sdk_setipcparam("/action/set?subject=pppoe",targetxml,function(result){if(result==true){parent.fun_show_tips_dialog(strsuc);}else if(result==400){parent.fun_show_tips_dialog(request,0);}else if(result==403){parent.fun_show_tips_dialog(auth,0);}else{parent.fun_show_tips_dialog(failed,0);}});}
function fun_restore_pppoe_parameters(){$("#input_user_name").val("");$("#input_password").val("");document.getElementById("check_enable_pppoe").checked='';$("#input_user_name,#input_password").attr("disabled","disabled");}