var timeredits=[];function timereidt(id){for(var index=0;index<timeredits.length;index++){if(id==timeredits[index].parentid){return timeredits[index];}}
var strhtml='<input id="'+id+'_hour"   class="ui-timer-widget" onkeydown="deal_timeredit_event(0,this.id)" onkeyup="deal_timeredit_event(1,this.id)" onchange="timer_value_change(this.id)" style="border: none;width: 22px;height: 100%;background-color: transparent;outline: none;margin-left: 4px;"  type="text" onfocus="this.select()" onmouseup="this.select()">:'+'<input id="'+id+'_minute" class="ui-timer-widget" onkeydown="deal_timeredit_event(0,this.id)" onkeyup="deal_timeredit_event(1,this.id)" onchange="timer_value_change(this.id)" style="border: none;width: 22px;height: 100%;background-color: transparent;outline: none;margin-left: 4px;"  type="text" onfocus="this.select()" onmouseup="this.select()">:'+'<input id="'+id+'_second" class="ui-timer-widget" onkeydown="deal_timeredit_event(0,this.id)" onkeyup="deal_timeredit_event(1,this.id)" onchange="timer_value_change(this.id)" style="border: none;width: 22px;height: 100%;background-color: transparent;outline: none;margin-left: 4px;"  type="text" onfocus="this.select()" onmouseup="this.select()">';document.getElementById(id).innerHTML=strhtml;$("#"+id).css({"border":"1px solid #242424","outline":"none"});var tempedit=new Object();tempedit.getvalue=timeredit_get_value;tempedit.parentid=id;tempedit.setvalue=timeredit_set_value;tempedit.valuechange=null;tempedit.disable=timeredit_disabled;timeredits[timeredits.length]=tempedit;return tempedit;}
function timeredit_get_value(){var strvalue="";var strsec1=$("#"+this.parentid+"_hour").val();var strsec2=$("#"+this.parentid+"_minute").val();var strsec3=$("#"+this.parentid+"_second").val();strvalue=strsec1+":"+strsec2+":"+strsec3;if(strsec1==""||strsec2==""||strsec3==""){return String("");}
return strvalue;}
function timeredit_set_value(val){var arrip=val.split(':');if(arrip.length!=3)
return false;var nhour,nminute,nsecond;if(arrip[0].length<2)
nhour="0"+arrip[0];else
nhour=arrip[0];if(arrip[1].length<2)
nminute="0"+arrip[1];else
nminute=arrip[1];if(arrip[2].length<2)
nsecond="0"+arrip[2];else
nsecond=arrip[2];document.getElementById(this.parentid+"_hour").value=nhour;document.getElementById(this.parentid+"_minute").value=nminute;document.getElementById(this.parentid+"_second").value=nsecond;if(nhour>=24){document.getElementById(this.parentid+"_minute").setAttribute("disabled","disabled");document.getElementById(this.parentid+"_second").setAttribute("disabled","disabled");}}
function timer_value_change(objid){var targetid=document.getElementById(objid).parentNode.id;for(var index=0;index<timeredits.length;index++){if(targetid==timeredits[index].parentid){if(timeredits[index].valuechange!=null){timeredits[index].valuechange();}}}
var arrname=String(objid).split('_');var curval=document.getElementById(objid).value;if(arrname[arrname.length-1]=="hour"){if(curval>24){document.getElementById(objid).value=curval[0];}}else if(arrname[arrname.length-1]=="minute"){if(curval>59){document.getElementById(objid).value=curval[0];}}else if(arrname[arrname.length-1]=="second"){if(curval>59){document.getElementById(objid).value=curval[0];}}}
function deal_timeredit_event(evtnum,id){var arrname=String(id).split('_');var currsec=arrname[arrname.length-1];var event=arguments.callee.caller.arguments[0]||window.event;if(evtnum==0){if(!(event.keyCode==46)&&!(event.keyCode==8)&&!(event.keyCode==37)&&!(event.keyCode==39))
if(!((event.keyCode>=48&&event.keyCode<=57)||(event.keyCode>=96&&event.keyCode<=105))){event.preventDefault();}}else{if(event.keyCode==186&&event.shiftKey){setTimeout(move_to_next_space(id),20);event.preventDefault();}
var currvalue=$("#"+id).val();if(arrname[arrname.length-1]=="hour"){if(currvalue>24){var realvalue=currvalue[0];var maxvalue=currvalue[0]+currvalue[1];if(maxvalue<=24){document.getElementById(id).value=maxvalue;}else{document.getElementById(id).value=realvalue;}
move_to_next_space(id);}else if(currvalue==24){document.getElementById(id.replace("hour","minute")).setAttribute("disabled","disabled");document.getElementById(id.replace("hour","second")).setAttribute("disabled","disabled");document.getElementById(id.replace("hour","minute")).value="00";document.getElementById(id.replace("hour","second")).value="00";}else if(currvalue<24){document.getElementById(id.replace("hour","minute")).removeAttribute("disabled");document.getElementById(id.replace("hour","second")).removeAttribute("disabled");if(currvalue.length>=2){move_to_next_space(id);}}}else{if(currvalue>59){var realvalue=currvalue[0];var maxvalue=currvalue[0]+currvalue[1];if(maxvalue<=59){document.getElementById(id).value=maxvalue;}else{document.getElementById(id).value=realvalue;}
move_to_next_space(id);}else{if(currvalue.length>=2){move_to_next_space(id);}}}}}
function move_to_next_space(id){var arrname=String(id).split('_');var currsec=arrname[arrname.length-1];var tagetid="";if(currsec=="hour"){tagetid=id.replace("hour","minute");document.getElementById(tagetid).focus();}else if(currsec=="minute"){tagetid=id.replace("minute","second");document.getElementById(tagetid).focus();}else if(currsec=="second"){tagetid=id.replace("second","hour");document.getElementById(tagetid).focus();}}
function timeredit_disabled(bdisable){if(bdisable){$("#"+this.parentid+"_hour").attr("disabled","disabled");$("#"+this.parentid+"_minute").attr("disabled","disabled");$("#"+this.parentid+"_second").attr("disabled","disabled");}else{$("#"+this.parentid+"_hour").removeAttr("disabled");$("#"+this.parentid+"_minute").removeAttr("disabled");$("#"+this.parentid+"_second").removeAttr("disabled");}}