$(window).ready(function(){fun_multilang_adapter();fun_get_nfs_parameters();fun_register_events();});function fun_multilang_adapter(){translate_page_item(TARGET_PAGE_COMMON,"restore","button_nfs_restore",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"save","button_nfs_save",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"refresh","button_nfs_refresh",ITEM_TYPE_VALUE);translate_page_item(TARGET_PAGE_COMMON,"enable","div_nfs_enable_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_COMMON,"status","div_nfs_status_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_NFS,"hostaddr","div_nfs_host_name",ITEM_TYPE_TEXT);translate_page_item(TARGET_PAGE_SUB_NFS,"rootpath","div_nfs_path_name",ITEM_TYPE_TEXT);input_edit_restriction("input_nfs_host",EDIT_RESTRICTION_XMLSTD,32);input_edit_restriction("input_nfs_path",EDIT_RESTRICTION_XMLSTD,32);}
function fun_register_events(){$("#check_enable_nfs").click(function(){fun_on_enable_change();});$("#button_nfs_restore").click(function(){fun_on_resotre();});$("#button_nfs_refresh").click(function(){fun_on_refresh();});$("#button_nfs_save").click(function(){fun_on_save();});}
function fun_get_nfs_parameters(){sdk_getipcparam("/action/get?subject=nfs",function(result){if(result==false)
return;$xml=$(result);var active=$xml.find("active").text();var host=$xml.find("host").text();var path=$xml.find("path").text();if(active==0){$("#input_nfs_host,#input_nfs_path").attr("disabled","disabled");}else{$("#input_nfs_host,#input_nfs_path").removeAttr("disabled");}
if(active==0){$("#check_enable_nfs").prop("checked",false);}else{$("#check_enable_nfs").prop("checked",true);}
if(host.length>0){$("#input_nfs_host").val(host);}
if(path.length>0){$("#input_nfs_path").val(path);}});sdk_getipcparam("/action/get?subject=diskinfo&id=1",function(result){if(result==false)
return;$xml=$(result);var disksta=$xml.find("status").text();var total=$xml.find("size").text();var usage=$xml.find("free").text();var percent,tagusagestring,tagtotalstring;var strused=translate_page_item(TARGET_PAGE_SUB_DISK,"usedsize","",ITEM_TYPE_NONE);var strtotal=translate_page_item(TARGET_PAGE_SUB_DISK,"unusedsize","",ITEM_TYPE_NONE);if(total>0){}else{}
var strabnormal=translate_page_item(TARGET_PAGE_SUB_DISK,"abnormal","",ITEM_TYPE_NONE);var strfull=translate_page_item(TARGET_PAGE_SUB_DISK,"full","",ITEM_TYPE_NONE);var umount=translate_page_item(TARGET_PAGE_SUB_NFS,"staumount","",ITEM_TYPE_NONE);var mounted=translate_page_item(TARGET_PAGE_SUB_NFS,"stamounted","",ITEM_TYPE_NONE);if(disksta&1){if(disksta&2&&!(disksta&4)&&!(disksta&8)){$("#div_nfs_status_value").text(mounted);}else if(disksta&2&&!(disksta&4)&&(disksta&8)){$("#div_nfs_status_value").text(strabnormal);}else if(disksta&2&&disksta&4){$("#div_nfs_status_value").text(strfull);}else if(!(disksta&2)){$("#div_nfs_status_value").text(umount);}}else{$("#div_nfs_status_value").text(umount);}});}
function fun_on_enable_change(){var enable=$("#check_enable_nfs").prop("checked")?1:0;if(enable==0){$("#input_nfs_host,#input_nfs_path").attr("disabled","disabled");}else{$("#input_nfs_host,#input_nfs_path").removeAttr("disabled");}}
function fun_on_resotre(){$("#check_enable_nfs").prop("checked",false);$("#input_nfs_host").attr("disabled","disabled");$("#input_nfs_path").attr("disabled","disabled");$("#input_nfs_host").val("");$("#input_nfs_path").val("");}
function fun_on_refresh(){fun_get_nfs_parameters();}
function fun_on_save(){var enable=$("#check_enable_nfs").prop("checked")?1:0;var host=$("#input_nfs_host").val();var path=$("#input_nfs_path").val();var targetxml='<?xml version="1.0" encoding="utf-8"?>'+'<request>'+'<nfs>'+'<active>'+enable+'</active>'+'<host>'+host+'</host>'+'<path>'+path+'</path>'+'</nfs>'+'</request>';sdk_setipcparam("/action/set?subject=nfs",targetxml,function(result){var strsuc=translate_page_item(TARGET_PAGE_TIPSTEXT,"infosave","",ITEM_TYPE_NONE);var request=translate_page_item(TARGET_PAGE_TIPSTEXT,"errrequest","",ITEM_TYPE_NONE);var auth=translate_page_item(TARGET_PAGE_TIPSTEXT,"errauthority","",ITEM_TYPE_NONE);var failed=translate_page_item(TARGET_PAGE_TIPSTEXT,"errset","",ITEM_TYPE_NONE);if(result==true){parent.fun_show_tips_dialog(strsuc);}else if(result==400){parent.fun_show_tips_dialog(request,0);}else if(result==403){parent.fun_show_tips_dialog(auth,0);}else{parent.fun_show_tips_dialog(failed,0);}});}